version: '3'
services:
  nodeapp:
    container_name: nodejs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm start